'use client';

import React, { useState, useMemo } from 'react';
import { useMyTickets } from '../../features/support/hooks/useSupport';
import { Card, CardContent } from '../ui/card';
import { Input } from '../ui/input';
import { Button } from '../ui/button';
import { 
  Search, Plus, Clock, MessageSquare, AlertCircle, CheckCircle2, ChevronRight, 
  HelpCircle, Phone, MessageCircle, Building2, ShieldCheck, CreditCard, 
  Banknote, Send, RefreshCw, FileText, ChevronDown, Sparkles, ExternalLink,
  MapPin, Globe, Headphones, ArrowRight, UserCheck
} from 'lucide-react';
import { formatDistanceToNow, format } from 'date-fns';
import { useRouter } from 'next/navigation';
import CreateTicketModal from './CreateTicketModal';
import { TicketStatus, TicketPriority } from '../../features/support/types';
import { cn } from '@/lib/utils';

interface FaqItem {
  id: string;
  category: 'CARDS' | 'CASH' | 'REMITTANCE' | 'SELL' | 'KYC';
  question: string;
  answer: string;
  steps?: string[];
  tag: string;
}

const FAQ_KNOWLEDGE_BASE: FaqItem[] = [
  {
    id: 'c1',
    category: 'CARDS',
    question: 'How do I set or reset the ATM PIN for my Forex Travel Card?',
    answer: 'You can instantly set or reset your 4-digit card PIN digitally through the ForexMate web portal or mobile app without visiting an ATM.',
    steps: [
      'Navigate to Dashboard → Forex Cards.',
      'Select your active card and click on "Card Security & PIN".',
      'Enter your new 4-digit PIN and verify with the 6-digit OTP sent to your registered mobile number.',
      'Your PIN is instantly activated globally for all chip & PIN point-of-sale machines and overseas ATMs.'
    ],
    tag: 'Forex Cards'
  },
  {
    id: 'c2',
    category: 'CARDS',
    question: 'How do I instantly reload currency on my Forex card while traveling abroad?',
    answer: 'ForexMate enables instant real-time wallet reload 24x7 from anywhere in the world at live interbank rates.',
    steps: [
      'Go to Dashboard → Forex Cards → Instant Reload.',
      'Select currency and enter the reload amount.',
      'Pay via Indian Net Banking, UPI, or Debit Card.',
      'Funds are loaded and converted into your card wallet within 15 minutes.'
    ],
    tag: 'Forex Cards'
  },
  {
    id: 'c3',
    category: 'CARDS',
    question: 'What should I do if my Forex card is lost or compromised overseas?',
    answer: 'Immediately freeze your card from your dashboard to prevent unauthorized transactions. You can also request an emergency backup card delivery or global emergency cash assistance.',
    steps: [
      'Open Forex Cards in Dashboard and click "Freeze / Lock Card" immediately.',
      'Call our 24x7 Overseas Emergency Hotline (+1-800-349-2819) or initiate a Live Staff Chat.',
      'Our team will block the card permanently and activate your secondary backup card in your welcome kit.'
    ],
    tag: 'Forex Cards'
  },
  {
    id: 'd1',
    category: 'CASH',
    question: 'How can I track my assigned doorstep delivery executive?',
    answer: 'Once your order is dispatched from our authorized vault branch, you receive a real-time live tracking link via SMS and WhatsApp with the delivery executive name, photo, phone number, and OTP.',
    steps: [
      'Open Active Orders in your dashboard.',
      'Click on your order to view live GPS status and delivery partner details.',
      'Share the 4-digit Delivery Verification OTP only after receiving and verifying your currency envelope.'
    ],
    tag: 'Currency Notes'
  },
  {
    id: 'd2',
    category: 'CASH',
    question: 'What documents do I need to present during cash delivery or branch pickup?',
    answer: 'As per Reserve Bank of India (RBI) regulations under the Foreign Exchange Management Act (FEMA), the traveller must present their original Government ID for physical verification.',
    steps: [
      'Original Indian PAN Card.',
      'Original Indian Passport (for overseas leisure/business travel).',
      'Confirmed Air Ticket copy or Student Visa (if applicable).'
    ],
    tag: 'Currency Notes'
  },
  {
    id: 'r1',
    category: 'REMITTANCE',
    question: 'How do I download the official SWIFT MT103 wire transfer confirmation copy?',
    answer: 'The official SWIFT MT103 receipt generated by the Reserve Bank Authorized Dealer Category-II banking network is automatically uploaded to your dashboard within 4 to 8 banking hours after wire dispatch.',
    steps: [
      'Go to Dashboard → Remittances.',
      'Click on your Remittance Reference ID.',
      'Click "Download SWIFT MT103 Copy (PDF)" to share with your university or overseas beneficiary.'
    ],
    tag: 'Remittances'
  },
  {
    id: 'r2',
    category: 'REMITTANCE',
    question: 'What is the RBI LRS Form A2 limit and TCS (Tax Collected at Source) rate?',
    answer: 'Under the RBI Liberalised Remittance Scheme (LRS), resident individuals can remit up to USD 250,000 per financial year.',
    steps: [
      'Education Remittance via Education Loan: 0.5% TCS on amounts exceeding ₹7 Lakhs.',
      'Self-Funded Education & Medical Remittance: 5% TCS on amounts exceeding ₹7 Lakhs.',
      'Other Remittances (Gifts, Maintenance): 20% TCS on amounts exceeding ₹7 Lakhs.',
      'All TCS paid can be claimed as a refund or credit against your annual Income Tax Return (ITR).'
    ],
    tag: 'Remittances'
  },
  {
    id: 's1',
    category: 'SELL',
    question: 'When will the INR payout be credited to my bank account after selling forex?',
    answer: 'Upon verification of physical currency notes at our vault branch or via our doorstep executive, funds are transferred instantly via IMPS / NEFT directly into your verified bank account (usually within 10 to 30 minutes).',
    steps: [
      'Handover currency notes to the authorized teller or doorstep executive.',
      'Executive verifies notes on counterfeit detection machine and issues digital receipt.',
      'Payout is triggered instantly to your bank account with UTR transaction number sent via SMS.'
    ],
    tag: 'Sell Forex'
  }
];

export default function SupportHub() {
  const { data: tickets, isLoading } = useMyTickets();
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedFaqCategory, setSelectedFaqCategory] = useState<'ALL' | 'CARDS' | 'CASH' | 'REMITTANCE' | 'SELL'>('ALL');
  const [expandedFaqId, setExpandedFaqId] = useState<string | null>('c1');
  const [isCreateModalOpen, setCreateModalOpen] = useState(false);
  const router = useRouter();

  const getStatusColor = (status: TicketStatus) => {
    switch (status) {
      case 'OPEN': return 'bg-blue-100 text-blue-800 border-blue-200';
      case 'WAITING_FOR_SUPPORT': return 'bg-yellow-100 text-yellow-800 border-yellow-200';
      case 'WAITING_FOR_CUSTOMER': return 'bg-purple-100 text-purple-800 border-purple-200';
      case 'IN_PROGRESS': return 'bg-orange-100 text-orange-800 border-orange-200';
      case 'ESCALATED': return 'bg-red-100 text-red-800 border-red-200';
      case 'RESOLVED': case 'CLOSED': return 'bg-green-100 text-green-800 border-green-200';
      default: return 'bg-gray-100 text-gray-800 border-gray-200';
    }
  };

  const getPriorityIcon = (priority: TicketPriority) => {
    switch (priority) {
      case 'CRITICAL': return <AlertCircle className="w-4 h-4 text-red-600" />;
      case 'HIGH': return <AlertCircle className="w-4 h-4 text-orange-600" />;
      case 'MEDIUM': return <AlertCircle className="w-4 h-4 text-yellow-600" />;
      case 'LOW': return <AlertCircle className="w-4 h-4 text-blue-600" />;
      default: return null;
    }
  };

  const activeTickets = tickets?.filter(t => !['CLOSED', 'CANCELLED', 'RESOLVED'].includes(t.status)) || [];
  const pastTickets = tickets?.filter(t => ['CLOSED', 'CANCELLED', 'RESOLVED'].includes(t.status)) || [];

  // Filter FAQs based on category & search query
  const filteredFaqs = useMemo(() => {
    return FAQ_KNOWLEDGE_BASE.filter(faq => {
      const matchesCategory = selectedFaqCategory === 'ALL' || faq.category === selectedFaqCategory;
      const matchesQuery = searchQuery === '' || 
        faq.question.toLowerCase().includes(searchQuery.toLowerCase()) ||
        faq.answer.toLowerCase().includes(searchQuery.toLowerCase()) ||
        faq.tag.toLowerCase().includes(searchQuery.toLowerCase());
      return matchesCategory && matchesQuery;
    });
  }, [selectedFaqCategory, searchQuery]);

  return (
    <div className="max-w-6xl mx-auto py-8 px-4 sm:px-6 space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500 font-sans">
      
      {/* Top Header */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-3xl font-extrabold tracking-tight text-gray-900">Support Desk &amp; Help Center</h1>
            <span className="bg-emerald-100 text-emerald-800 text-xs font-black px-2.5 py-0.5 rounded-full flex items-center gap-1">
              <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span> Staff Active
            </span>
          </div>
          <p className="text-gray-500 text-sm mt-1">Connect directly with ForexMate support officers, vault branch managers, and access 24x7 self-serve solutions.</p>
        </div>
        
        <div className="flex items-center gap-3">
          <a
            href="tel:9212219191"
            className="hidden sm:flex items-center gap-2 bg-slate-100 hover:bg-slate-200 text-slate-800 font-extrabold text-xs px-4 py-3 rounded-xl border border-slate-300 transition-colors"
          >
            <Phone className="w-4 h-4 text-slate-600" />
            <span>Call 9212219191</span>
          </a>
          <Button 
            onClick={() => setCreateModalOpen(true)} 
            className="bg-amber-500 hover:bg-amber-400 text-slate-950 font-extrabold h-11 px-6 rounded-xl shadow-md hover:scale-105 transition-all"
          >
            <Plus className="w-5 h-5 mr-2" />
            Raise Support Ticket
          </Button>
        </div>
      </div>

      {/* Hero Search Box */}
      <Card className="border-none shadow-xl shadow-blue-900/10 bg-gradient-to-br from-[#0a2540] via-[#0d3b66] to-[#001e3d] text-white overflow-hidden relative rounded-3xl">
        <div className="absolute top-0 right-0 w-96 h-96 bg-amber-500/10 rounded-full blur-3xl pointer-events-none" />
        <CardContent className="p-8 md:p-10 text-center relative z-10 space-y-4">
          <div className="w-12 h-12 rounded-2xl bg-white/10 backdrop-blur-md flex items-center justify-center mx-auto text-amber-400 border border-white/15 shadow-inner">
            <Headphones className="w-6 h-6" />
          </div>
          <h2 className="text-2xl md:text-3xl font-extrabold">How can our support team help you?</h2>
          <p className="text-slate-300 text-xs md:text-sm max-w-xl mx-auto font-medium">
            Search our knowledge base or select a quick topic below for instant resolution.
          </p>
          
          <div className="max-w-2xl mx-auto relative pt-2">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400 w-5 h-5" />
            <Input 
              className="w-full h-13 pl-12 pr-4 rounded-2xl bg-white text-gray-900 text-sm shadow-xl focus:ring-4 focus:ring-amber-400/40 border-0 font-medium" 
              placeholder="Search for answers, e.g. 'How to reset card PIN', 'SWIFT tracking'..." 
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
          </div>

          {/* Quick Filter Topic Pills */}
          <div className="flex flex-wrap justify-center gap-2 pt-2">
            {['Card PIN Reset', 'Instant Reload', 'Delivery Tracking', 'SWIFT MT103 Copy', 'Bank Payout', 'Lost Card Freeze'].map((pill) => (
              <button
                key={pill}
                type="button"
                onClick={() => setSearchQuery(pill)}
                className="text-[11px] font-bold bg-white/10 hover:bg-white/20 border border-white/20 px-3 py-1 rounded-full text-slate-200 transition-colors"
              >
                {pill}
              </button>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Direct Contact Channels Grid (Connect to Staff) */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h3 className="text-lg font-extrabold text-gray-900 flex items-center gap-2">
            <Headphones className="w-5 h-5 text-amber-600" />
            Direct Support Channels &amp; Staff Contact
          </h3>
          <span className="text-xs text-gray-500 font-bold">24x7 Priority Support</span>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          
          {/* Channel 1: 24x7 Phone Helpline */}
          <div className="bg-white border border-slate-200 hover:border-amber-400 rounded-2xl p-5 shadow-xs hover:shadow-md transition-all space-y-3 flex flex-col justify-between">
            <div>
              <div className="w-10 h-10 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center mb-3">
                <Phone className="w-5 h-5" />
              </div>
              <h4 className="font-extrabold text-slate-900 text-sm">24x7 Toll-Free Helpline</h4>
              <p className="text-xs text-slate-500 font-medium mt-1">
                Instant telephone assistance for orders, emergencies &amp; card hotlisting.
              </p>
            </div>
            <div className="pt-2 border-t border-slate-100 space-y-1.5">
              <a
                href="tel:9212219191"
                className="block text-center w-full py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-xs font-extrabold transition-colors shadow-xs"
              >
                Call +91 9212219191
              </a>
              <span className="block text-[10px] text-center text-slate-400 font-semibold">Toll-Free: 1800-102-4418</span>
            </div>
          </div>

          {/* Channel 2: WhatsApp Support */}
          <div className="bg-white border border-slate-200 hover:border-emerald-400 rounded-2xl p-5 shadow-xs hover:shadow-md transition-all space-y-3 flex flex-col justify-between">
            <div>
              <div className="w-10 h-10 rounded-xl bg-emerald-50 text-emerald-600 flex items-center justify-center mb-3">
                <MessageCircle className="w-5 h-5" />
              </div>
              <h4 className="font-extrabold text-slate-900 text-sm">WhatsApp Concierge</h4>
              <p className="text-xs text-slate-500 font-medium mt-1">
                Quick updates on live rates, order status, and KYC document uploads.
              </p>
            </div>
            <div className="pt-2 border-t border-slate-100">
              <a
                href="https://wa.me/918882947806?text=Hi%20ForexMate%20Team%2C%20I%20need%20help%20with%20my%20forex%20order."
                target="_blank"
                rel="noopener noreferrer"
                className="block text-center w-full py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-xs font-extrabold transition-colors shadow-xs"
              >
                Chat on WhatsApp
              </a>
            </div>
          </div>

          {/* Channel 3: Live Staff Chat */}
          <div className="bg-white border border-slate-200 hover:border-purple-400 rounded-2xl p-5 shadow-xs hover:shadow-md transition-all space-y-3 flex flex-col justify-between">
            <div>
              <div className="w-10 h-10 rounded-xl bg-purple-50 text-purple-600 flex items-center justify-center mb-3">
                <MessageSquare className="w-5 h-5" />
              </div>
              <h4 className="font-extrabold text-slate-900 text-sm">Live Staff Desk</h4>
              <p className="text-xs text-slate-500 font-medium mt-1">
                Chat with a ForexMate operational officer directly from your dashboard.
              </p>
            </div>
            <div className="pt-2 border-t border-slate-100">
              <button
                type="button"
                onClick={() => setCreateModalOpen(true)}
                className="w-full py-2 bg-purple-600 hover:bg-purple-700 text-white rounded-xl text-xs font-extrabold transition-colors shadow-xs"
              >
                Start Support Chat
              </button>
            </div>
          </div>

          {/* Channel 4: Vault Branch Visit / Manager */}
          <div className="bg-white border border-slate-200 hover:border-amber-400 rounded-2xl p-5 shadow-xs hover:shadow-md transition-all space-y-3 flex flex-col justify-between">
            <div>
              <div className="w-10 h-10 rounded-xl bg-amber-50 text-amber-600 flex items-center justify-center mb-3">
                <Building2 className="w-5 h-5" />
              </div>
              <h4 className="font-extrabold text-slate-900 text-sm">Branch Manager Desk</h4>
              <p className="text-xs text-slate-500 font-medium mt-1">
                Visit our authorized vault branches in Delhi, Mumbai, Bengaluru &amp; 150+ cities.
              </p>
            </div>
            <div className="pt-2 border-t border-slate-100">
              <button
                type="button"
                onClick={() => router.push('/branches')}
                className="w-full py-2 bg-slate-900 hover:bg-slate-800 text-white rounded-xl text-xs font-extrabold transition-colors shadow-xs"
              >
                Locate Branch Vault
              </button>
            </div>
          </div>

        </div>
      </div>

      {/* Interactive FAQ Knowledge Base */}
      <div className="space-y-5 pt-2">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div>
            <h3 className="text-lg font-extrabold text-gray-900 flex items-center gap-2">
              <HelpCircle className="w-5 h-5 text-blue-600" />
              Frequently Asked Questions &amp; Knowledge Base
            </h3>
            <p className="text-xs text-gray-500 font-medium">Instant solutions to common queries</p>
          </div>

          {/* Category Tabs */}
          <div className="flex flex-wrap gap-1 bg-slate-100 p-1 rounded-xl">
            {[
              { id: 'ALL', label: 'All Topics' },
              { id: 'CARDS', label: 'Forex Cards' },
              { id: 'CASH', label: 'Currency Notes' },
              { id: 'REMITTANCE', label: 'Remittances' },
              { id: 'SELL', label: 'Sell Forex' },
            ].map(tab => (
              <button
                key={tab.id}
                type="button"
                onClick={() => setSelectedFaqCategory(tab.id as any)}
                className={`px-3 py-1.5 rounded-lg text-xs font-extrabold transition-all ${
                  selectedFaqCategory === tab.id
                    ? 'bg-white text-slate-900 shadow-2xs'
                    : 'text-slate-600 hover:text-slate-900'
                }`}
              >
                {tab.label}
              </button>
            ))}
          </div>
        </div>

        {/* FAQ Accordion List */}
        <div className="space-y-3">
          {filteredFaqs.length > 0 ? (
            filteredFaqs.map(faq => {
              const isExpanded = expandedFaqId === faq.id;
              return (
                <div
                  key={faq.id}
                  className={`border rounded-2xl transition-all duration-200 overflow-hidden ${
                    isExpanded 
                      ? 'bg-blue-50/40 border-blue-300 shadow-xs' 
                      : 'bg-white border-slate-200 hover:border-slate-300'
                  }`}
                >
                  <button
                    type="button"
                    onClick={() => setExpandedFaqId(isExpanded ? null : faq.id)}
                    className="w-full p-4 sm:p-5 text-left flex items-center justify-between gap-4"
                  >
                    <div className="flex items-center gap-3">
                      <span className="text-xs font-black px-2.5 py-0.5 rounded-md bg-slate-100 text-slate-700 uppercase">
                        {faq.tag}
                      </span>
                      <span className="font-extrabold text-sm text-slate-900">{faq.question}</span>
                    </div>
                    <ChevronDown className={`w-4 h-4 text-slate-500 transition-transform shrink-0 ${isExpanded ? 'rotate-180 text-blue-600' : ''}`} />
                  </button>

                  {isExpanded && (
                    <div className="px-4 sm:px-5 pb-5 pt-1 text-xs text-slate-700 space-y-3 animate-in fade-in duration-200">
                      <p className="font-medium leading-relaxed">{faq.answer}</p>
                      
                      {faq.steps && faq.steps.length > 0 && (
                        <div className="bg-white p-3.5 rounded-xl border border-blue-100 space-y-1.5">
                          <p className="font-extrabold text-slate-900 text-[11px] uppercase tracking-wider">Step-by-step instructions:</p>
                          <ol className="list-decimal list-inside space-y-1 text-slate-600 font-medium">
                            {faq.steps.map((step, idx) => (
                              <li key={idx}>{step}</li>
                            ))}
                          </ol>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              );
            })
          ) : (
            <div className="p-8 text-center bg-white border border-slate-200 rounded-2xl text-slate-500 text-xs font-medium">
              No matching articles found for "{searchQuery}". You can raise a support ticket to get personal assistance.
            </div>
          )}
        </div>
      </div>

      {/* Active Cases / Tickets Section */}
      <div className="space-y-4 pt-4">
        <div className="flex items-center justify-between">
          <h3 className="text-lg font-extrabold text-gray-900 flex items-center gap-2">
            <MessageSquare className="w-5 h-5 text-blue-600" />
            Your Active Support Cases ({activeTickets.length})
          </h3>
          <Button 
            onClick={() => setCreateModalOpen(true)}
            variant="outline" 
            size="sm"
            className="text-xs font-bold"
          >
            + New Case
          </Button>
        </div>
        
        {isLoading ? (
          <div className="space-y-3">
            {[1,2].map(i => <div key={i} className="h-20 bg-gray-100 rounded-2xl animate-pulse"></div>)}
          </div>
        ) : activeTickets.length === 0 ? (
          <Card className="border-dashed border-2 border-gray-200 bg-gray-50/50 rounded-2xl">
            <CardContent className="p-8 text-center space-y-2">
              <div className="w-12 h-12 bg-emerald-100 rounded-full flex items-center justify-center mx-auto text-emerald-600 font-black">
                ✓
              </div>
              <p className="text-gray-900 font-bold text-sm">No active support cases</p>
              <p className="text-gray-500 text-xs">All your previous inquiries are resolved. If you need help, feel free to create a case anytime.</p>
            </CardContent>
          </Card>
        ) : (
          <div className="grid gap-3">
            {activeTickets.map(ticket => (
              <div 
                key={ticket.id} 
                onClick={() => router.push(`/dashboard/support/${ticket.id}`)}
                className="group bg-white border border-gray-200 hover:border-blue-300 rounded-2xl p-5 shadow-xs hover:shadow-md cursor-pointer transition-all duration-200"
              >
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                  <div className="flex-1">
                    <div className="flex items-center gap-3 mb-1.5">
                      <span className="text-xs font-mono font-bold text-gray-500 bg-gray-100 px-2 py-0.5 rounded">{ticket.ticketNumber}</span>
                      <span className={cn("text-[11px] font-bold px-2.5 py-0.5 rounded-full border", getStatusColor(ticket.status))}>
                        {ticket.status.replace(/_/g, ' ')}
                      </span>
                      {getPriorityIcon(ticket.priority)}
                    </div>
                    <h4 className="text-base font-extrabold text-gray-900 group-hover:text-blue-600 transition-colors">{ticket.subject}</h4>
                    <p className="text-xs text-gray-500 mt-1 line-clamp-1">{ticket.category.name} • {ticket.description}</p>
                  </div>
                  <div className="flex items-center gap-6 md:border-l md:pl-6 border-gray-100">
                    <div className="text-right">
                      <p className="text-[10px] font-semibold text-gray-400 uppercase tracking-wider mb-0.5">Last Updated</p>
                      <p className="text-xs font-bold text-gray-800 flex items-center justify-end">
                        <Clock className="w-3.5 h-3.5 mr-1 text-gray-400" />
                        {formatDistanceToNow(new Date(ticket.updatedAt))} ago
                      </p>
                    </div>
                    <div className="w-9 h-9 rounded-full bg-gray-50 group-hover:bg-blue-50 flex items-center justify-center transition-colors">
                      <ChevronRight className="w-4 h-4 text-gray-400 group-hover:text-blue-600" />
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Emergency Overseas Support Box */}
      <div className="bg-gradient-to-r from-slate-900 to-slate-800 text-white rounded-3xl p-6 sm:p-8 space-y-4 shadow-lg">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-amber-500 text-slate-950 flex items-center justify-center font-bold">
            <Globe className="w-5 h-5" />
          </div>
          <div>
            <h4 className="font-extrabold text-sm sm:text-base">International Overseas Emergency Hotlines</h4>
            <p className="text-xs text-slate-300">Toll-free numbers for travelers facing issues while abroad</p>
          </div>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 pt-2">
          <div className="bg-white/10 p-3 rounded-xl border border-white/10 text-center">
            <span className="text-[10px] text-amber-300 font-bold uppercase block">USA / Canada</span>
            <span className="text-xs font-black text-white">+1-800-349-2819</span>
          </div>
          <div className="bg-white/10 p-3 rounded-xl border border-white/10 text-center">
            <span className="text-[10px] text-amber-300 font-bold uppercase block">UK / Europe</span>
            <span className="text-xs font-black text-white">+44-800-048-8921</span>
          </div>
          <div className="bg-white/10 p-3 rounded-xl border border-white/10 text-center">
            <span className="text-[10px] text-amber-300 font-bold uppercase block">UAE / Gulf</span>
            <span className="text-xs font-black text-white">+971-4-289-1020</span>
          </div>
          <div className="bg-white/10 p-3 rounded-xl border border-white/10 text-center">
            <span className="text-[10px] text-amber-300 font-bold uppercase block">Singapore / AU</span>
            <span className="text-xs font-black text-white">+65-3158-9210</span>
          </div>
        </div>
      </div>

      {isCreateModalOpen && (
        <CreateTicketModal 
          isOpen={isCreateModalOpen} 
          onClose={() => setCreateModalOpen(false)} 
        />
      )}
    </div>
  );
}
